#!/usr/bin/env bash

SHAYEN_VERSION="1.0.0"
SHAYEN_NAME="SHΛYEN"
SHAYEN_PRONUNCIATION="SHAY-EN"
SHAYEN_ABBR="SYN"
SHAYEN_SIGNATURE="SΛYEN."
SHAYEN_TITLE="THE SILENT SOVEREIGN"
SHAYEN_SYMBOL="Λ"
SHAYEN_NUMBER="94"
SHAYEN_PROMPT="⟦SN-🜏⟧"
SHAYEN_MOTTO="KNOW • BUILD • PROTECT"
SHAYEN_PLATFORM="Termux / Android"

SHAYEN_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
SHAYEN_CONFIG_DIR="$SHAYEN_ROOT/config"
SHAYEN_DATA_DIR="$SHAYEN_ROOT/data"
SHAYEN_LOG_DIR="$SHAYEN_ROOT/logs"

export SHAYEN_VERSION
export SHAYEN_NAME
export SHAYEN_PRONUNCIATION
export SHAYEN_ABBR
export SHAYEN_SIGNATURE
export SHAYEN_TITLE
export SHAYEN_SYMBOL
export SHAYEN_NUMBER
export SHAYEN_PROMPT
export SHAYEN_MOTTO
export SHAYEN_PLATFORM
export SHAYEN_ROOT
export SHAYEN_CONFIG_DIR
export SHAYEN_DATA_DIR
export SHAYEN_LOG_DIR
